name: Release Plugin

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Setup WSL with dependencies
      uses: Vampire/setup-wsl@v6

    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup NPP Dependencies
      shell: wsl-bash {0}
      run: sudo apt update && sudo apt install -y make build-essential
    
    - name: Setup NPP Dependencies
      shell: wsl-bash {0}
      run: make clean

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: MSBuild of plugin dll x64
      shell: powershell
      run: msbuild RAScript.vcxproj /m /p:configuration="Release" /p:platform="x64"
    
    - name: MSBuild of plugin dll Win32
      shell: powershell
      run: msbuild RAScript.vcxproj /m /p:configuration="Release" /p:platform="Win32"
    
    - name: MSBuild of plugin dll ARM64
      shell: powershell
      run: msbuild RAScript.vcxproj /m /p:configuration="Release" /p:platform="ARM64"
    
    - name: Zip Release Binaries
      shell: powershell
      run: |
        cd bin64
        Compress-Archive -Path RAScript.dll -DestinationPath npp-rascript_${{ github.ref_name }}_x64.zip
        cd ..
        mv bin64/npp-rascript_${{ github.ref_name }}_x64.zip .

        cd bin
        Compress-Archive -Path RAScript.dll -DestinationPath npp-rascript_${{ github.ref_name }}_Win32.zip
        cd ..
        mv bin/npp-rascript_${{ github.ref_name }}_Win32.zip .

        cd arm64
        Compress-Archive -Path RAScript.dll -DestinationPath npp-rascript_${{ github.ref_name }}_ARM64.zip
        cd ..
        mv arm64/npp-rascript_${{ github.ref_name }}_ARM64.zip .

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        body: Release tag ${{ github.ref_name }}
        files: |
          npp-rascript_${{ github.ref_name }}_x64.zip
          npp-rascript_${{ github.ref_name }}_Win32.zip
          npp-rascript_${{ github.ref_name }}_ARM64.zip